/* 🍕 مدیریت و نمایش اندازه‌های پیتزا — یکپارچه */
(function(){
'use strict';
const U='https://bjpascssizuskiujnzvf.supabase.co',K='sb_publishable_VMPe2QDMNfdwwAEAYQ2Y4A_3idOGTvrK';
const labels={one:'👤 یک‌نفره',two:'👥 دو‌نفره',family:'👨‍👩‍👧 خانواده'};
let db=null,sizes={},pizzaCats=new Set(),ready=false;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
function getDb(){if(db)return db;try{if(window.supabase?.createClient)db=window.supabase.createClient(U,K)}catch(e){}return db}
function foods(){try{if(typeof window.foods!=='undefined'&&Array.isArray(window.foods))return window.foods}catch(e){}return []}
function cart(){try{if(typeof window.cart!=='undefined'&&Array.isArray(window.cart))return window.cart}catch(e){}return []}
function saveCart(){try{if(typeof window.saveCart==='function')window.saveCart()}catch(e){}}
async function loadData(){const c=getDb();if(!c)return false;const [cr,sr]=await Promise.all([c.from('categories').select('id,name').eq('active',true),c.from('pizza_sizes').select('food_id,one_price,two_price,family_price')]);if(cr.error||sr.error)return false;pizzaCats=new Set((cr.data||[]).filter(x=>/پیتزا|pizza/i.test(String(x.name||''))).map(x=>Number(x.id)));sizes=Object.fromEntries((sr.data||[]).map(x=>[String(x.food_id),x]));ready=true;return true}
function isPizza(f){return !!f&&pizzaCats.has(Number(f.category_id))}
function getSizes(id){const p=sizes[String(id)];if(!p)return[];return Object.entries({one:p.one_price,two:p.two_price,family:p.family_price}).filter(([,v])=>Number(v)>0).map(([key,v])=>({key,label:labels[key],price:Number(v)}))}
function addSize(food,key){const f=foods().find(x=>Number(x.id)===Number(food.id));const p=sizes[String(food.id)];if(!f||!p)return;const price=Number(p[key+'_price']||0);if(price<=0||f.stock_status==='soldout')return;const id=-(Number(f.id)*10+({one:1,two:2,family:3}[key]||9));const cs=cart(),name=f.name+' — '+labels[key],old=cs.find(x=>Number(x.id)===id);if(old)old.q=(Number(old.q)||0)+1;else cs.push({id,name,price,q:1,pizzaSize:key,pizzaFoodId:Number(f.id)});saveCart();try{window.renderCart?.();window.updateCartUI?.()}catch(e){}}
function decorate(){if(!ready||!$('grid'))return;document.querySelectorAll('#grid .card').forEach(card=>{if(card.querySelector('.pizza-size-block'))return;const title=card.querySelector('.body h3')?.textContent?.trim();const f=foods().find(x=>String(x.name||'').trim()===title&&isPizza(x));if(!f)return;const ss=getSizes(f.id);if(!ss.length)return;const old=card.querySelector('.price');if(old)old.textContent='انتخاب اندازه';const add=card.querySelector('.add');if(add)add.style.display='none';const block=document.createElement('div');block.className='pizza-size-block';block.innerHTML='<div class="pizza-size-title">🍕 اندازه و قیمت</div><div class="pizza-size-list">'+ss.map(s=>'<button class="pizza-size-btn" type="button"><span>'+esc(s.label)+'</span><strong>'+s.price.toLocaleString('fa-AF')+' افغانی</strong></button>').join('')+'</div>';ss.forEach((s,i)=>{const b=block.querySelectorAll('button')[i];if(b)b.onclick=()=>addSize(f,s.key)});card.querySelector('.body')?.appendChild(block)})}
function patchCustomer(){['setCat','draw','renderFoods'].forEach(name=>{const fn=window[name];if(typeof fn!=='function'||fn.__pizza)return;const wrapped=function(){const r=fn.apply(this,arguments);setTimeout(decorate,50);return r};wrapped.__pizza=true;window[name]=wrapped})}
/* مدیریت: قیمت‌ها داخل ویرایش همان پیتزا ذخیره می‌شوند؛ هیچ پنل جداگانه‌ای ساخته نمی‌شود. */
function patchAdmin(){if(!$('foods'))return;window.loadSizes=async function(id){const c=getDb();if(!c)return;const r=await c.from('pizza_sizes').select('one_price,two_price,family_price').eq('food_id',id).maybeSingle();if(r.error)return;const p=r.data||{};if($('s1_'+id))$('s1_'+id).value=p.one_price??'';if($('s2_'+id))$('s2_'+id).value=p.two_price??'';if($('sf_'+id))$('sf_'+id).value=p.family_price??''};window.savePizza=async function(id){try{const name=$('pn_'+id)?.value.trim(),price=Number($('pp_'+id)?.value||0),description=$('pd_'+id)?.value.trim()||null;if(!name)return;let image_url=null;if($('pf_'+id)?.files?.[0]){const file=$('pf_'+id).files[0],path='site/'+crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await getDb().storage.from('food-images').upload(path,file,{upsert:false});if(up.error)throw up.error;image_url=getDb().storage.from('food-images').getPublicUrl(path).data.publicUrl}const data={name,price,description};if(image_url)data.image_url=image_url;let r=await getDb().from('foods').update(data).eq('id',id);if(r.error)throw r.error;const vals={one_price:Number($('s1_'+id)?.value||0),two_price:Number($('s2_'+id)?.value||0),family_price:Number($('sf_'+id)?.value||0)};r=await getDb().from('pizza_sizes').upsert({food_id:id,...vals},{onConflict:'food_id'});if(r.error)throw r.error;sizes[String(id)]={food_id:id,...vals};const msg=$('pm_'+id);if(msg){msg.textContent='✅ اطلاعات، ترکیبات و قیمت‌های پیتزا ذخیره شد.';msg.style.color='#197a4b'}if(typeof window.loadFoods==='function')await window.loadFoods($('fc')?.value)}catch(e){const msg=$('pm_'+id);if(msg){msg.textContent='❌ '+e.message;msg.style.color='#b52b2b'}}};
}
async function boot(){await loadData();if($('foods'))patchAdmin();patchCustomer();let n=0;const t=setInterval(()=>{patchCustomer();decorate();if(++n>120)clearInterval(t)},250);decorate()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,50));else setTimeout(boot,50);
})();