/* 🍕 Pizza sizes: one-person / two-person / family */
(function(){
  const SIZE_LABELS={one:'👤 یک‌نفره',two:'👥 دو‌نفره',family:'👨‍👩‍👧‍👦 خانواده'};
  const SB_URL='https://bjpascssizuskiujnzvf.supabase.co',SB_KEY='sb_publishable_VMPe2QDMNfdwwAEAYQ2Y4A_3idOGTvrK';
  let pizzaSizes={};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
  async function fetchSizes(){try{if(!window.supabase||!window.sb)return;const r=await window.sb.from('pizza_sizes').select('food_id,one_price,two_price,family_price');if(!r.error)pizzaSizes=Object.fromEntries((r.data||[]).map(x=>[String(x.food_id),x]));}catch(_){}}
  function sizesFor(f){const p=pizzaSizes[String(f.id)];if(!p)return[];return Object.entries({one:p.one_price,two:p.two_price,family:p.family_price}).filter(([,v])=>v!==null&&v!==undefined&&Number(v)>0).map(([key,v])=>({key,label:SIZE_LABELS[key],price:Number(v)}));}
  function isPizza(f){return !!pizzaSizes[String(f.id)]||/پیتزا/i.test(f.cat||'');}
  window.addPizzaToCart=function(id,key){const f=window.foods?.find(x=>String(x.id)===String(id)),p=pizzaSizes[String(id)];if(!f||!p||f.stock_status==='soldout')return;const price=Number(p[key+'_price']||0);if(!price)return;const cartKey=`pz:${id}:${key}`,old=window.cart.find(x=>String(x.id)===cartKey);if(old)old.q++;else window.cart.push({id:cartKey,food_id:f.id,name:`${f.name} — ${SIZE_LABELS[key]}`,price,q:1,pizzaSize:key});window.saveCart();};
  function renderPizza(){if(!window.foods||!window.$||!window.active)return;const d=window.active==='همه'?window.foods:window.foods.filter(f=>f.cat===window.active);const grid=window.$('grid');if(!grid)return;grid.innerHTML=d.length?d.map(f=>{const sizes=isPizza(f)?sizesFor(f):[];const actions=sizes.length?`<div class="pizza-sizes">${sizes.map(s=>`<button class="pizza-size" type="button" onclick="addPizzaToCart(${f.id},'${s.key}')"><span>${esc(s.label)}</span><strong>${window.fa(s.price)} افغانی</strong></button>`).join('')}</div>`:`<div class="row"><span class="price">${window.fa(f.price)} افغانی</span><button class="add" ${f.stock_status==='soldout'?'disabled':''} onclick="add(${f.id})">+</button></div>`;return`<article class="card"><div class="photo">${f.image_url?`<img src="${esc(f.image_url)}" loading="lazy" decoding="async" alt="${esc(f.name)}">`:''}<span class="badge ${f.stock_status||'available'}">${window.st[f.stock_status]||'موجود'}</span></div><div class="body"><h3>${esc(f.name)}</h3><div class="desc">${esc(f.description||'')}</div>${sizes.length?'<div class="pizza-size-title">🍕 انتخاب اندازه و قیمت</div>':''}${actions}</div></article>`}).join(''):'<div class="empty">در این دسته غذایی نیست.</div>';if(window.bar)window.bar();};
  function adminPanel(){const app=document.getElementById('foods');if(!app||document.getElementById('pizzaSizeAdmin')||!window.supabase)return;const panel=document.createElement('div');panel.id='pizzaSizeAdmin';panel.className='pizza-size-admin';panel.innerHTML='<h3>🍕 اندازه و قیمت پیتزا</h3><p class="muted">هر اندازه‌ای که قیمت نداشته باشد برای مشتری نمایش داده نمی‌شود.</p><div class="field"><label>پیتزا</label><select id="pzFood"></select></div><div class="pz-grid"><div class="field"><label>👤 یک‌نفره</label><input id="pzOne" type="number" min="0"></div><div class="field"><label>👥 دو‌نفره</label><input id="pzTwo" type="number" min="0"></div><div class="field"><label>👨‍👩‍👧‍👦 خانواده</label><input id="pzFamily" type="number" min="0"></div></div><button class="btn gold" id="pzSave">💾 ذخیره قیمت‌های پیتزا</button><p id="pzMsg" class="statusmsg"></p>';app.appendChild(panel);const load=async()=>{const cats=(await window.sb.from('categories').select('id,name').order('sort_order')).data||[];const pc=cats.find(c=>String(c.name||'').includes('پیتزا'));const foods=(await window.sb.from('foods').select('id,name,category_id').eq('category_id',pc?.id||-1).order('sort_order')).data||[];pzFood.innerHTML=foods.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');const one=async()=>{const id=Number(pzFood.value);if(!id)return;pzOne.value=pzTwo.value=pzFamily.value='';const r=await window.sb.from('pizza_sizes').select('*').eq('food_id',id).maybeSingle();if(r.data){pzOne.value=r.data.one_price??'';pzTwo.value=r.data.two_price??'';pzFamily.value=r.data.family_price??'';}};pzFood.onchange=one;if(foods.length)await one();pzSave.onclick=async()=>{const id=Number(pzFood.value);if(!id)return;const payload={food_id:id,one_price:Number(pzOne.value)||null,two_price:Number(pzTwo.value)||null,family_price:Number(pzFamily.value)||null};const r=await window.sb.from('pizza_sizes').upsert(payload,{onConflict:'food_id'});pzMsg.textContent=r.error?'❌ '+r.error.message:'✅ قیمت‌های پیتزا ذخیره شد.';if(!r.error){pizzaSizes[String(id)]=payload;}}};load();}
  const css=document.createElement('style');css.textContent='.pizza-size-title{font-size:13px;font-weight:900;color:#a66b00;margin:12px 0 8px}.pizza-sizes{display:grid;gap:8px;margin-top:8px}.pizza-size{width:100%;display:flex;justify-content:space-between;align-items:center;gap:8px;border:1px solid #e5a72c;border-radius:12px;background:#fffaf0;color:#071b3d;padding:10px 11px;font:inherit;cursor:pointer}.pizza-size strong{color:#071b3d}.pizza-size:hover{background:#071b3d;color:#fff}.pizza-size:hover strong{color:#f5c54d}.pizza-size-admin{margin-top:16px;padding:16px;border:1px solid #e5b53b;border-radius:14px;background:#fff}.pizza-size-admin .pz-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:10px 0}@media(max-width:700px){.pizza-size-admin .pz-grid{grid-template-columns:1fr}}';document.head.appendChild(css);
  async function boot(){await fetchSizes();if(document.getElementById('foods'))adminPanel();else setTimeout(renderPizza,100);}
  window.addEventListener('load',boot,{once:true});setTimeout(boot,1200);
})();