(()=>{
const css=`.reviews{margin:10px 0 60px}.reviews-box{background:#fff;border-radius:24px;padding:24px;box-shadow:0 10px 35px #07172f12;border:1px solid #eee}.reviews h2{margin:0;color:#07172f;font-size:26px}.reviews-sub{color:#697386;margin:8px 0 22px}.rating-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.rating-item{background:#f7f8fa;border-radius:16px;padding:15px;text-align:center}.rating-item b{display:block;margin-bottom:8px;color:#07172f}.stars{display:flex;direction:rtl;justify-content:center;gap:3px}.stars button{border:0;background:transparent;font-size:25px;padding:0 2px;color:#c9ced7}.stars button.on{color:#d8a83e}.review-text{width:100%;min-height:100px;resize:vertical;margin-top:16px;border:1px solid #dfe3e9;border-radius:13px;padding:12px;font:inherit}.review-actions{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:12px}.review-submit{border:0;background:#07172f;color:#fff;border-radius:12px;padding:11px 18px;font-weight:900}.review-msg{color:#2c7a4b;font-size:13px}@media(max-width:800px){.rating-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.rating-grid{grid-template-columns:1fr}.reviews-box{padding:18px}}`;
const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
const wrap=document.createElement('section');wrap.className='reviews';wrap.innerHTML=`<div class="reviews-box"><h2>⭐ نظر و امتیاز مهمانان</h2><p class="reviews-sub">تجربه خود را درباره غذا، نوشیدنی، محیط و مهمان‌نوازی با ما در میان بگذارید.</p><div class="rating-grid">${[['food','🍽️ غذا'],['drink','🥤 آبمیوه و نوشیدنی'],['place','🏛️ محیط'],['service','🤝 مهمان‌نوازی']].map(([id,label])=>`<div class="rating-item"><b>${label}</b><div class="stars" data-rating="${id}">${[5,4,3,2,1].map(n=>`<button type="button" data-value="${n}" aria-label="${n} ستاره">★</button>`).join('')}</div></div>`).join('')}</div><textarea id="reviewText" class="review-text" placeholder="نظر یا پیشنهاد شما چیست؟"></textarea><div class="review-actions"><span id="reviewMsg" class="review-msg"></span><button class="review-submit" type="button" id="reviewSubmit">ثبت نظر</button></div></div>`;
const info=document.querySelector('.info');(info?.parentNode||document.querySelector('main'))?.insertBefore(wrap,info||null);
const ratings={food:0,drink:0,place:0,service:0};
wrap.querySelectorAll('.stars').forEach(box=>{const key=box.dataset.rating;box.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{ratings[key]=Number(btn.dataset.value);box.querySelectorAll('button').forEach(b=>b.classList.toggle('on',Number(b.dataset.value)<=ratings[key]));});});
wrap.querySelector('#reviewSubmit').onclick=()=>{const text=wrap.querySelector('#reviewText').value.trim();if(!Object.values(ratings).every(Boolean)){alert('لطفاً برای هر بخش امتیاز بدهید.');return}if(!text){alert('لطفاً نظر یا پیشنهاد خود را بنویسید.');return}const reviews=JSON.parse(localStorage.getItem('hh_reviews')||'[]');reviews.push({ratings,text,createdAt:new Date().toISOString()});localStorage.setItem('hh_reviews',JSON.stringify(reviews));wrap.querySelector('#reviewText').value='';Object.keys(ratings).forEach(k=>ratings[k]=0);wrap.querySelectorAll('.stars button').forEach(b=>b.classList.remove('on'));wrap.querySelector('#reviewMsg').textContent='نظر شما با موفقیت ثبت شد. ممنون از همراهی شما 🌹';setTimeout(()=>wrap.querySelector('#reviewMsg').textContent='',4000)};
})();
