from pathlib import Path
p=Path('admin.html')
s=p.read_text(encoding='utf-8')
if "tab('access')" in s:
    print('access bar already integrated')
    raise SystemExit(0)
nav='<button class="btn" onclick="tab(\'access\')">⚡ دسترسی آسان</button>'
needle='<button class="btn" onclick="tab(\'waiter\')">🔔 گارسون</button>'
s=s.replace(needle, needle+nav, 1)
section='''<section id="access" class="panel hide"><h2>⚡ مدیریت دسترسی آسان</h2><p class="muted">از اینجا نوار پایینی سایت را کامل مدیریت کن: اضافه، ویرایش، حذف، عکس، آیکون، فعال/غیرفعال و ترتیب.</p><div class="grid"><div class="field"><label>عنوان</label><input id="ab_title"></div><div class="field"><label>توضیح</label><input id="ab_subtitle"></div><div class="field"><label>آیکون</label><input id="ab_icon" value="⚡"></div><div class="field"><label>شکل نمایش</label><select id="ab_style"><option value="icon">آیکون</option><option value="image">عکس</option><option value="both">عکس + آیکون</option></select></div><div class="field"><label>لینک/عمل</label><input id="ab_url" placeholder="مثلاً tel:... یا https://..."></div><div class="field"><label>ترتیب</label><input id="ab_order" type="number" value="1"></div><div class="field"><label>🖼️ عکس</label><input id="ab_file" type="file" accept="image/*"><img id="ab_preview" class="preview"></div></div><button class="btn gold" onclick="addAccessItem()">+ افزودن مورد</button><p id="ab_msg" class="statusmsg"></p><div id="accessList"></div></section>'''
needle2='<section id="site" class="panel">'
s=s.replace(needle2, section+needle2, 1)
js='''async function loadAccess(){let r=await sb.from('access_bar_items').select('*').order('sort_order');if(r.error){accessList.innerHTML='<p>'+esc(r.error.message)+'</p>';return}accessList.innerHTML=(r.data||[]).map(x=>`<div class="item row"><div style="flex:1"><b>${esc(x.icon||'')} ${esc(x.title)}</b><div class="muted">${esc(x.subtitle||'')} | ترتیب: ${x.sort_order} | ${x.active?'فعال':'خاموش'}</div>${x.image_url?`<img class="thumb" src="${esc(x.image_url)}">`:''}</div><button class="btn gold" onclick="editAccessItem(${x.id})">✏️ ویرایش</button><button class="btn ${x.active?'danger':'ok'}" onclick="toggleAccess(${x.id},${x.active})">${x.active?'خاموش':'فعال'}</button><button class="btn danger" onclick="delAccess(${x.id})">حذف</button></div>`).join('')||'<p class="muted">موردی نیست.</p>'}async function addAccessItem(){try{let image_url=await upload(ab_file.files[0]);let r=await sb.from('access_bar_items').insert({title:ab_title.value.trim(),subtitle:ab_subtitle.value.trim(),icon:ab_icon.value.trim(),style:ab_style.value,action_url:ab_url.value.trim()||null,sort_order:Number(ab_order.value||0),active:true,image_url});if(r.error)throw r.error;ab_title.value='';ab_subtitle.value='';ab_icon.value='⚡';ab_url.value='';ab_file.value='';m('ab_msg','✅ مورد دسترسی آسان اضافه شد.','#197a4b');loadAccess()}catch(e){m('ab_msg','❌ '+e.message,'#b52b2b')}}async function editAccessItem(id){let r=await sb.from('access_bar_items').select('*').eq('id',id).single();if(r.error)return alert(r.error.message);let x=r.data;let title=prompt('عنوان:',x.title);if(title===null)return;let subtitle=prompt('توضیح:',x.subtitle||'');if(subtitle===null)return;let order=prompt('ترتیب:',x.sort_order);if(order===null)return;let u=await sb.from('access_bar_items').update({title:title.trim(),subtitle:subtitle.trim(),sort_order:Number(order)||0}).eq('id',id);if(u.error)alert(u.error.message);loadAccess()}async function toggleAccess(id,v){let r=await sb.from('access_bar_items').update({active:!v}).eq('id',id);if(r.error)alert(r.error.message);loadAccess()}async function delAccess(id){if(confirm('این مورد از دسترسی آسان حذف شود؟')){let r=await sb.from('access_bar_items').delete().eq('id',id);if(r.error)alert(r.error.message);loadAccess()}}\n'''
s=s.replace('async function loadSite(){',js+'async function loadSite(){',1)
s=s.replace("['site','slides','foods','cats','orders','waiter']","['site','access','slides','foods','cats','orders','waiter']",1)
s=s.replace('await loadSite();await loadCats();','await loadSite();await loadAccess();await loadCats();',1)
p.write_text(s,encoding='utf-8')
print('patched admin.html')
